# -*- coding: utf-8 -*-
"""Buinoza_DA8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKWrZqh6VpMzCST3e2A7ZCFTPAUmxOa8

<center><font size="6"><b>Комп'ютерний практикум 8.

<center><b> Створення дашборду за допомогою Streamlit </font>
"""
# -*- coding: utf-8 -*-

import streamlit as st
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import altair as alt

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Завантаження даних
df = pd.read_csv('HR_comma_sep.csv')
df.rename(columns={"average_montly_hours": "average_monthly_hours"}, inplace=True)

# Налаштування сторінки
st.set_page_config(
    page_title="HR Insight Dashboard",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get Help': 'https://docs.streamlit.io/',
        'Report a bug': 'https://github.com/streamlit/streamlit/issues',
        'About': 'Інтерактивна панель для аналізу працівників і ризику звільнення'
    }
)

# Бічна панель / SIDEBAR
st.sidebar.title("Панель фільтрації")
st.sidebar.markdown("🔍 **Фільтруйте працівників за ключовими ознаками:**")
st.sidebar.markdown("Цей дашборд допомагає дослідити задоволеність, навантаження та ризики звільнень по департаментах.")

selected_departments = st.sidebar.multiselect(
    "Оберіть департаменти:",
    options=sorted(df["Department"].unique()),
    default=sorted(df["Department"].unique())
)

salary_options = ["Усі"] + sorted(df["salary"].unique())
selected_salary = st.sidebar.selectbox("Рівень зарплати:", salary_options)

status_filter = st.sidebar.radio("Статус працівника:", ["Усі", "Працює", "Звільнився"])

filter_accident_free = st.sidebar.checkbox("🩺 Лише без нещасних випадків")

max_years = int(df["time_spend_company"].max())
selected_years = st.sidebar.slider("Максимальний стаж (роки в компанії):", 1, max_years, max_years)

chart_option = st.sidebar.radio(
    "📊 Оберіть графік для перегляду:",
    [
        "Залежність змінних (scatter + тренд)",
        "Огляд департаменту/ів",
        "Розподіл працівників"
    ]
)

st.sidebar.markdown("---")
st.sidebar.markdown("**Інструкція:** \nОберіть фільтри, щоб переглянути статистику департаменту та ймовірність звільнення працівників.")
st.sidebar.markdown("👩‍💻 **Автор**: Буйноза Олена")

# Фільтрація
filtered = df[
    df["Department"].isin(selected_departments) &
    ((df["salary"] == selected_salary) if selected_salary != "Усі" else True) &
    (
        (status_filter == "Усі") |
        ((status_filter == "Працює") & (df["left"] == 0)) |
        ((status_filter == "Звільнився") & (df["left"] == 1))
    ) &
    ((df["Work_accident"] == 0) if filter_accident_free else True) &
    (df["time_spend_company"] <= selected_years)
]

st.title("📊 HR Insight Dashboard")
st.subheader(f"🔍 Відфільтровано {len(filtered)} працівників")

csv = filtered.to_csv(index=False).encode("utf-8")
st.download_button("⬇️ Завантажити CSV", csv, "filtered_employees.csv", "text/csv")

# Таблиця
st.subheader("Оберіть, які стовпці таблиці відображати")
all_columns = filtered.columns.tolist()
def_columns = ["Department", "salary", "satisfaction_level", "last_evaluation", "average_monthly_hours", "time_spend_company", "left"]
selected_cols = st.multiselect("Оберіть стовпці для перегляду:", all_columns, default=[c for c in def_columns if c in all_columns])

if selected_cols:
    st.dataframe(filtered[selected_cols])
else:
    st.info("Оберіть хоча б один стовпець, щоб побачити таблицю.")

# Графіки



elif chart_option == "Огляд департаменту/ів":
    st.subheader("Огляд департаменту/ів")

   # Розрахунок метрик
    total_employees = len(filtered)
    left_employees = filtered["left"].sum()
    turnover_rate = (left_employees / total_employees) * 100 if total_employees else 0
    avg_satisfaction = filtered["satisfaction_level"].mean()
    avg_projects = filtered["number_project"].mean()
    avg_hours = filtered["average_monthly_hours"].mean()
    
    # Виведення в колонках
    st.subheader("📊 Основні показники працівників")
    
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("👥 Загальна кількість", total_employees)
        st.metric("📌 Середня кількість проєктів", f"{avg_projects:.2f}")
    with col2:
        st.metric("👋 Звільнилося", left_employees)
        st.metric("⏱ Середні години/міс", f"{avg_hours:.1f}")
    with col3:
        st.metric("📉 Рівень плинності", f"{turnover_rate:.1f}%")
        st.metric("😊 Середня задоволеність", f"{avg_satisfaction:.2f}")



        # Розподіл задоволеності
    st.subheader("😊 Розподіл рівня задоволеності працівників")
    fig = px.histogram(
        filtered,
        x="satisfaction_level",
        nbins=20,
        title="Розподіл задоволеності",
        labels={"satisfaction_level": "Рівень задоволеності", "к-ть працівників": "Кількість працівників"}
    )
    fig.update_layout(bargap=0.1)
    st.plotly_chart(fig, use_container_width=True)



elif chart_option == "Розподіл працівників":
    st.subheader("📊 Розподіл працівників за департаментами")
    dept_share = filtered["Department"].value_counts(normalize=True).reset_index()
    dept_share.columns = ["Департамент", "Частка"]
    fig1 = px.pie(dept_share, values="Частка", names="Департамент", title="Частка по департаментах", hole=0.4)
    st.plotly_chart(fig1, use_container_width=True)

    st.subheader("💰 Розподіл працівників за рівнем зарплати")
    sal_share = filtered["salary"].value_counts(normalize=True).reset_index()
    sal_share.columns = ["Рівень зарплати", "Частка"]
    fig2 = px.pie(sal_share, values="Частка", names="Рівень зарплати", title="Частка по зарплаті", hole=0.4)
    st.plotly_chart(fig2, use_container_width=True)

# Класифікаційна модель
st.sidebar.markdown("🔬 **Побудова моделі класифікації**")
st.sidebar.markdown("Оберіть ознаки, за якими модель прогнозуватиме, чи працівник звільниться.")

numeric_cols = filtered.select_dtypes(include=np.number).columns.tolist()
if "left" in numeric_cols:
    numeric_cols.remove("left")
selected_features = st.sidebar.multiselect("Ознаки для моделі (X):", options=numeric_cols, default=["satisfaction_level", "last_evaluation"])
build_model = st.sidebar.checkbox("🔍 Побудувати модель класифікації")

if build_model:
    st.subheader("🔍 Класифікація: прогноз ймовірності звільнення")
    if selected_features and "left" in filtered.columns:
        df_model = filtered[selected_features + ["left"]].dropna()
        if len(df_model) >= 10:
            X = df_model[selected_features]
            y = df_model["left"]
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)
            model = LogisticRegression()
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            acc = model.score(X_test, y_test)

            st.markdown(f"**Точність моделі:** {acc:.2%}")
            st.markdown("**Матриця помилок:**")
            st.write(confusion_matrix(y_test, y_pred))

            report = classification_report(y_test, y_pred, output_dict=True)
            st.markdown("**Звіт класифікації:**")
            st.dataframe(pd.DataFrame(report).transpose())
        else:
            st.warning("Недостатньо даних для побудови моделі (мінімум 10 рядків).")
    else:
        st.warning("Оберіть хоча б одну ознаку для побудови моделі.")
