# -*- coding: utf-8 -*-
"""Buinoza_DA8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKWrZqh6VpMzCST3e2A7ZCFTPAUmxOa8

<center><font size="6"><b>Комп'ютерний практикум 8.

<center><b> Створення дашборду за допомогою Streamlit </font>
"""

# Завантажимо Streamlit (не додавати в .py файл додатку)
!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import altair as alt

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_csv('HR_comma_sep.csv')

df.info()

df.describe()

missing_data = df.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

st.set_page_config(
    page_title="HR Insight Dashboard",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get Help': 'https://docs.streamlit.io/',
        'Report a bug': 'https://github.com/streamlit/streamlit/issues',
        'About': 'Інтерактивна панель для аналізу працівників і ризику звільнення'
    }
)

# Бічна панель / SIDEBAR
st.sidebar.title("Панель фільтрації")

# Інформаційний опис
st.sidebar.markdown("🔍 **Фільтруйте працівників за ключовими ознаками:**")
st.sidebar.markdown("Цей дашборд допомагає дослідити задоволеність, навантаження та ризики звільнень по департаментах.")

# 1. Вибір одного департаменту
selected_department = st.sidebar.selectbox(
    "Оберіть департамент:",
    sorted(df["Department"].unique())
)

# 2. Вибір кількох рівнів зарплати
selected_salary = st.sidebar.multiselect(
    "Рівень зарплати:",
    options=df["salary"].unique(),
    default=df["salary"].unique()
)

# 3. Радіо-кнопки: статус працівника
status_filter = st.sidebar.radio(
    "Статус працівника:",
    ["Усі", "Працює", "Звільнився"]
)

# 4. Прапорець: тільки без нещасних випадків
filter_accident_free = st.sidebar.checkbox("🩺 Лише без нещасних випадків")

# 5. Слайдер: обмежити стаж
max_years = int(df["time_spend_company"].max())
selected_years = st.sidebar.slider(
    "Максимальний стаж (роки в компанії):",
    min_value=1,
    max_value=max_years,
    value=max_years
)

# 6. Вибір типу графіка
chart_option = st.sidebar.radio(
    "📊 Оберіть графік для перегляду:",
    [
        "Залежність змінних (scatter + тренд)",
        "Профіль департаменту (радар)",
        "Середній показник по роках у компанії"
    ]
)

# Автор і інструкція
st.sidebar.markdown("---")
st.sidebar.markdown("**Інструкція:** \nОберіть фільтри, щоб переглянути статистику департаменту та ймовірність звільнення працівників.")
st.sidebar.markdown("👩‍💻 **Автор**: Буйноза Олена :)")

# Створюємо df_filtered за вибраними параметрами
df_filtered = df[
    (df["Department"] == selected_department) &
    (df["salary"].isin(selected_salary)) &
    (
        (status_filter == "Усі") |
        ((status_filter == "Працює") & (df["left"] == 0)) |
        ((status_filter == "Звільнився") & (df["left"] == 1))
    ) &
    ((df["Work_accident"] == 0) if filter_accident_free else True) &
    (df["time_spend_company"] <= selected_years)
]

# Виведемо розмір фільтрованого датасету (опційно)
st.write(f"📋 Відфільтровано {len(df_filtered)} записів.")

# Блок класифікації
st.sidebar.markdown("🔬 **Побудова моделі класифікації**")
st.sidebar.markdown("Оберіть ознаки, за якими модель прогнозуватиме, чи працівник звільниться.")

# Обираємо лише числові колонки, окрім 'left'
numeric_columns = df_filtered.select_dtypes(include=np.number).columns.tolist()
if 'left' in numeric_columns:
    numeric_columns.remove('left')  # бо це ціль

# Вибір змінних для моделі
selected_features = st.sidebar.multiselect(
    "Ознаки для моделі (X):",
    options=numeric_columns,
    default=["satisfaction_level", "last_evaluation"]
)

# Кнопка побудови моделі
build_model = st.sidebar.checkbox("🔍 Побудувати модель класифікації")

# Основна панель

st.title("📊 HR Insight Dashboard")
st.subheader(f"🔍 Відфільтровано {df_filtered.shape[0]} працівників")

# Кнопка завантаження CSV
csv = df_filtered.to_csv(index=False).encode("utf-8")
st.download_button(
    label="⬇️ Завантажити CSV",
    data=csv,
    file_name="filtered_employees.csv",
    mime="text/csv"
)

# Інтерактивна таблиця
st.subheader("Оберіть, які стовпці таблиці відображати")

all_columns = df_filtered.columns.tolist()
default_columns = [
    "Department", "salary", "satisfaction_level",
    "last_evaluation", "average_monthly_hours",
    "time_spend_company", "left"
]

selected_columns = st.multiselect(
    "Оберіть стовпці для перегляду:",
    options=all_columns,
    default=[col for col in default_columns if col in all_columns]
)

if selected_columns:
    st.dataframe(df_filtered[selected_columns])
else:
    st.info("Оберіть хоча б один стовпець, щоб побачити таблицю.")



# Графіки

if chart_option == "Залежність змінних (scatter + тренд)":
    st.subheader("📊 Залежність між двома змінними")

    x_var = st.selectbox("Оберіть змінну для осі X:", df_filtered.select_dtypes(include=np.number).columns)
    y_var = st.selectbox("Оберіть змінну для осі Y:", df_filtered.select_dtypes(include=np.number).columns)

    fig = px.scatter(df_filtered, x=x_var, y=y_var, color=df_filtered["left"].map({0: "Працює", 1: "Звільнився"}))
    fig.update_traces(marker=dict(size=8))
    fig.update_layout(title=f"Залежність {y_var} від {x_var}", legend_title="Статус")
    st.plotly_chart(fig, use_container_width=True)

elif chart_option == "Профіль департаменту (радар)":
    st.subheader("📊 Профіль департаменту")

    radar_metrics = ["satisfaction_level", "last_evaluation", "average_monthly_hours", "time_spend_company"]
    dept_data = df_filtered[radar_metrics].mean().values.tolist()
    overall_data = df[radar_metrics].mean().values.tolist()

    radar_df = pd.DataFrame({
        "Метрика": radar_metrics,
        "Департамент": dept_data,
        "Загалом": overall_data
    })

    fig = px.line_polar(radar_df, r="Департамент", theta="Метрика", line_close=True, name="Департамент")
    fig.add_scatterpolar(r=radar_df["Загалом"], theta=radar_df["Метрика"], mode="lines", name="Загалом")
    st.plotly_chart(fig, use_container_width=True)

elif chart_option == "Середній показник по роках у компанії":
    st.subheader("📈 Середній показник по стажу (роках у компанії)")

    metric_choice = st.selectbox("Оберіть показник:", [
        "satisfaction_level", "last_evaluation", "average_monthly_hours", "left"
    ])

    grouped = df_filtered.groupby("time_spend_company")[metric_choice].mean().reset_index()
    fig = px.line(grouped, x="time_spend_company", y=metric_choice, markers=True,
                  labels={"time_spend_company": "Роки в компанії", metric_choice: "Середнє значення"},
                  title=f"{metric_choice} залежно від стажу")
    st.plotly_chart(fig, use_container_width=True)

# Побудова класифікаційної моделі
if build_model:
    st.subheader("🔍 Класифікація: прогноз ймовірності звільнення")

    if selected_features and "left" in df_filtered.columns:
        df_model = df_filtered[selected_features + ["left"]].dropna()

        if df_model.shape[0] >= 10:
            # Формування X та y
            X = df_model[selected_features]
            y = df_model["left"]

            # Розділення на тренувальну і тестову вибірки
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

            # Побудова моделі
            model = LogisticRegression()
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            accuracy = model.score(X_test, y_test)

            # Вивід результатів
            st.markdown(f"**Точність моделі:** {accuracy:.2%}")
            st.markdown("**Матриця помилок:**")
            st.write(confusion_matrix(y_test, y_pred))

            # Звіт
            report = classification_report(y_test, y_pred, output_dict=True)
            st.markdown("**Звіт класифікації:**")
            st.dataframe(pd.DataFrame(report).transpose())

        else:
            st.warning("Недостатньо даних для побудови моделі (мінімум 10 рядків).")
    else:
        st.warning("Оберіть хоча б одну ознаку для побудови моделі.")

"""##<center>__Самостійні завдання__</center>

> Скопіювати блок самостійних завдань в окремий файл ***LastName_DA8.py***

> Інсталюйте необхідні пакети бібліотек Python збережіть у файл `requirements.txt`

> завантажте файл зі статистичного банку даних, з яким будете працювати `data.csv`

### Завдання

1. Створіть dashboard, як додаток у **Streamlit Community Cloud**
2. Додаток має містити: панель фільтрації з елементами
- Заголовок      
- Текстовий опис / інструкції                       
- Один вибір зі списку                              
- Кілька виборів                                   
- Вибір одного варіанту з декількох (радіо-кнопки)  
- Прапорець        
3. В головній частині: таблиця, як результат фільтрів з можливістю вибору колонок
4. Графічне представлення (мінімум 3 типи графіки)
5. Реалізація регресійної моделі або інших (кластеризації/класифікації)                        
6. Створені файли мають бути розміщені в репрозиторії GitHub, та імплементуватися в Streamlit Community Cloud
"""